kind: Template
apiVersion: v1
metadata:
  name: snowdrop-site-angular
  annotations:
    openshift.io/display-name: "Snowdrop Site - Angular"
    description: This application contains the website for the Snowdrop project
    tags: instant-app,snowdrop-site
    iconClass: icon-shadowman
    template.openshift.io/long-description: This application contains the website for the Snowdrop project
    template.openshift.io/provider-display-name: Red Hat, Inc.
    template.openshift.io/documentation-url: https://github.com/snowdrop/snowdrop-site-angular
    template.openshift.io/support-url: https://access.redhat.com
message: "The following service has been created in your project: snowdrop-site-angular.\n\nFor more information about using this template, including OpenShift considerations, see https://github.com/snowdrop/snowdrop-site-angular"
labels:
  template: snowdrop-site-angular
parameters:
- name: IMAGE
  value: snowdrop/snowdrop-site-angular
  required: true
- name: IMAGE_TAG
  value: latest
  required: true
objects:
- kind: DeploymentConfig
  apiVersion: v1
  metadata:
    name: snowdrop-site-angular
    annotations:
      configmap.fabric8.io/update-on-change: "launcher"
  spec:
    replicas: 1
    selector:
      service: snowdrop-site-angular
    strategy:
      resources: {}
      rollingParams:
        intervalSeconds: 1
        maxSurge: 25%
        maxUnavailable: 25%
        timeoutSeconds: 600
        updatePeriodSeconds: 1
      type: Rolling
    template:
      metadata:
        labels:
          service: snowdrop-site-angular
      spec:
        containers:
        - image: ${IMAGE}:${IMAGE_TAG}
          imagePullPolicy: Always
          name: snowdrop-site-angular
          ports:
          - containerPort: 8080
            protocol: TCP
          env:
          - name: LAUNCHER_BACKEND_URL
            valueFrom:
              configMapKeyRef:
                name: launcher
                key: launcher.backend.url
          - name: LAUNCHER_MISSIONCONTROL_URL
            valueFrom:
              configMapKeyRef:
                name: launcher
                key: launcher.missioncontrol.url
          - name: LAUNCHER_KEYCLOAK_URL
            valueFrom:
              configMapKeyRef:
                name: launcher
                key: launcher.keycloak.url
          - name: LAUNCHER_KEYCLOAK_REALM
            valueFrom:
              configMapKeyRef:
                name: launcher
                key: launcher.keycloak.realm
          - name: LAUNCHER_TRACKER_SEGMENT_TOKEN
            valueFrom:
              configMapKeyRef:
                name: launcher
                key: launcher.tracker.segment.token
          resources: {}
          terminationMessagePath: /dev/termination-log
          readinessProbe:
            httpGet:
              path: /launch/wizard
              port: 8080
            initialDelaySeconds: 15
            timeoutSeconds: 10
            periodSeconds: 20
          livenessProbe:
            httpGet:
              path: /launch/wizard
              port: 8080
            initialDelaySeconds: 30
            timeoutSeconds: 10
            periodSeconds: 20
        restartPolicy: Always
        dnsPolicy: ClusterFirst
        securityContext: {}
        terminationGracePeriodSeconds: 30
    test: false
    triggers:
    - type: ConfigChange
- kind: Service
  apiVersion: v1
  metadata:
    labels:
      service: snowdrop-site-angular
    name: snowdrop-site-angular
  spec:
    ports:
    - name: "8080"
      port: 8080
      protocol: TCP
      targetPort: 8080
    selector:
      service: snowdrop-site-angular
    sessionAffinity: None
    type: ClusterIP
